/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as TgicccInfoRouteImport } from './routes/tgiccc-info'
import { Route as StructureLegitimacyRouteImport } from './routes/structure-legitimacy'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ImpactsBenefitsRouteImport } from './routes/impacts-benefits'
import { Route as DirectorsMessageRouteImport } from './routes/directors-message'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const TgicccInfoRoute = TgicccInfoRouteImport.update({
  id: '/tgiccc-info',
  path: '/tgiccc-info',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureLegitimacyRoute = StructureLegitimacyRouteImport.update({
  id: '/structure-legitimacy',
  path: '/structure-legitimacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactsBenefitsRoute = ImpactsBenefitsRouteImport.update({
  id: '/impacts-benefits',
  path: '/impacts-benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorsMessageRoute = DirectorsMessageRouteImport.update({
  id: '/directors-message',
  path: '/directors-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/directors-message': typeof DirectorsMessageRoute
  '/impacts-benefits': typeof ImpactsBenefitsRoute
  '/media': typeof MediaRoute
  '/organization': typeof OrganizationRoute
  '/structure-legitimacy': typeof StructureLegitimacyRoute
  '/tgiccc-info': typeof TgicccInfoRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/directors-message': typeof DirectorsMessageRoute
  '/impacts-benefits': typeof ImpactsBenefitsRoute
  '/media': typeof MediaRoute
  '/organization': typeof OrganizationRoute
  '/structure-legitimacy': typeof StructureLegitimacyRoute
  '/tgiccc-info': typeof TgicccInfoRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/directors-message': typeof DirectorsMessageRoute
  '/impacts-benefits': typeof ImpactsBenefitsRoute
  '/media': typeof MediaRoute
  '/organization': typeof OrganizationRoute
  '/structure-legitimacy': typeof StructureLegitimacyRoute
  '/tgiccc-info': typeof TgicccInfoRoute
  '/vision-mission': typeof VisionMissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/directors-message'
    | '/impacts-benefits'
    | '/media'
    | '/organization'
    | '/structure-legitimacy'
    | '/tgiccc-info'
    | '/vision-mission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/directors-message'
    | '/impacts-benefits'
    | '/media'
    | '/organization'
    | '/structure-legitimacy'
    | '/tgiccc-info'
    | '/vision-mission'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/directors-message'
    | '/impacts-benefits'
    | '/media'
    | '/organization'
    | '/structure-legitimacy'
    | '/tgiccc-info'
    | '/vision-mission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DirectorsMessageRoute: typeof DirectorsMessageRoute
  ImpactsBenefitsRoute: typeof ImpactsBenefitsRoute
  MediaRoute: typeof MediaRoute
  OrganizationRoute: typeof OrganizationRoute
  StructureLegitimacyRoute: typeof StructureLegitimacyRoute
  TgicccInfoRoute: typeof TgicccInfoRoute
  VisionMissionRoute: typeof VisionMissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tgiccc-info': {
      id: '/tgiccc-info'
      path: '/tgiccc-info'
      fullPath: '/tgiccc-info'
      preLoaderRoute: typeof TgicccInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure-legitimacy': {
      id: '/structure-legitimacy'
      path: '/structure-legitimacy'
      fullPath: '/structure-legitimacy'
      preLoaderRoute: typeof StructureLegitimacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacts-benefits': {
      id: '/impacts-benefits'
      path: '/impacts-benefits'
      fullPath: '/impacts-benefits'
      preLoaderRoute: typeof ImpactsBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directors-message': {
      id: '/directors-message'
      path: '/directors-message'
      fullPath: '/directors-message'
      preLoaderRoute: typeof DirectorsMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DirectorsMessageRoute: DirectorsMessageRoute,
  ImpactsBenefitsRoute: ImpactsBenefitsRoute,
  MediaRoute: MediaRoute,
  OrganizationRoute: OrganizationRoute,
  StructureLegitimacyRoute: StructureLegitimacyRoute,
  TgicccInfoRoute: TgicccInfoRoute,
  VisionMissionRoute: VisionMissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
